name: CMake build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: DEBUG

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conf:
          - option: "-DMEMSAN=1"
            make-target: "test-san"
          - option: "-DMEMSAN=0"
            make-target: "test"
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.conf.option}}

      - name: Build
        run: sudo apt-get install libboost-all-dev && cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run:  make ${{matrix.conf.make-target}}
